name: server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  shelf: ^1.4.0
  googleapis_auth: ^2.0.0
  dotenv: ^4.1.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
