// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwBaQ9Z7idjBeo_bciPdhMNGP0I5n5PMM',
    appId: '1:518330283384:web:d3cd11f6daf0f29afd048d',
    messagingSenderId: '518330283384',
    projectId: 'social-learning-32741',
    authDomain: 'social-learning-32741.firebaseapp.com',
    storageBucket: 'social-learning-32741.appspot.com',
    measurementId: 'G-SFXK4L6LD1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa2M7Zwf7aKi_Db8Nn9G0ncJNZAMRAFwk',
    appId: '1:518330283384:android:602df8be06096757fd048d',
    messagingSenderId: '518330283384',
    projectId: 'social-learning-32741',
    storageBucket: 'social-learning-32741.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQxT4skbrhahQHEMoDbgDpJvpVKG9BVY',
    appId: '1:518330283384:ios:2bf27cb952c003a0fd048d',
    messagingSenderId: '518330283384',
    projectId: 'social-learning-32741',
    storageBucket: 'social-learning-32741.appspot.com',
    iosClientId: '518330283384-rg6sb9ek7vsc7gf8s9j1mnnng5vrj9l1.apps.googleusercontent.com',
    iosBundleId: 'com.playposse.sociallearning.socialLearning',
  );
}
