import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:social_learning/state/course_designer_state.dart';
import 'package:social_learning/ui_foundation/helper_widgets/course_designer/course_designer_card.dart';
import 'package:social_learning/ui_foundation/helper_widgets/dialog_utils.dart';
import 'package:social_learning/ui_foundation/helper_widgets/general/blocking_spinner_dialog.dart';

class SkillRubricInfoCard extends StatelessWidget {
  const SkillRubricInfoCard({super.key});

  Future<void> _onAIPressed(BuildContext context) async {
    final state = context.read<CourseDesignerState>();
    final hasDegrees =
        state.skillRubric?.dimensions.any((d) => d.degrees.isNotEmpty) ?? false;
    if (hasDegrees) {
      await DialogUtils.showInfoDialog(
        context,
        'AI skill rubric generation',
        'This AI function can only be used for an empty skill rubric.\n\nDelete your existing skill degrees to proceed.',
        () {},
      );
    } else {
      await DialogUtils.showConfirmationDialog(
        context,
        'AI skill rubric generation',
        'Your skill dimensions and degrees will be auto\u2011generated by AI.',
        () async {
          BlockingSpinnerDialog.show(context);
          await state.generateSkillRubric();
          Navigator.of(context).pop();
        },
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return CourseDesignerCard(
      title: 'Step 5: Skill Rubric',
      titleIcon: Tooltip(
        message: 'Generate with AI',
        child: InkWell(
          borderRadius: BorderRadius.circular(4),
          onTap: () => _onAIPressed(context),
          child: const Padding(
            padding: EdgeInsets.all(4.0),
            child: Icon(Icons.auto_fix_high, size: 16, color: Colors.grey),
          ),
        ),
      ),
      body: const Text(
        'Acquiring knowledge and developing skills are key to mastering '
        'a subject. Here, you can define the skills that develop a master. Each '
        'skill dimension can be broken into a degree of mastery. For each degree, '
        'you can list exercises (lessons) that help the student progress to the '
        'next degree.\n\n'
        'For example, pole dancing involves knowledge of moves and technique. '
        'It also requires developing skill in strength, flexibility, and '
        'body coordination. In a skill dimension like musicality, what a '
        'novice needs to develop to the next degree is different from what '
        'an advanced student needs.\n\n'
        'Plus: You\'ll be able to assess students based on the skills '
        'rubric. The app will generate a radar chart, which quickly '
        'communicates to you and the student where their '
        'strength/weaknesses are.',
      ),
    );
  }
}
